theme: jekyll-theme-architect
show_downloads: true
zip_url: https://github.com/nyteshade/KeyCertExtractor/blob/master/KeyCertExtractor.app.zip?raw=true
tar_url: https://github.com/nyteshade/KeyCertExtractor/blob/master/KeyCertExtractor.app.zip?raw=true
